version: "3"
services:
  #
  # API/Controller
  #
  api-dev:
    image: node:erbium
    environment:
      PORT: ${API_PORT}
      AGENT_ADMIN_URL: ${AGENT_ADMIN_URL}
      AGENT_ADMIN_API_KEY: ${AGENT_ADMIN_API_KEY}
      #AGENT_ADMIN_AUTH_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ3YWxsZXRfaWQiOiJmYTcyOTA0MC1lZmY4LTQ4OGMtOGQ4Ny04OTFjNjAzNjU2YzcifQ.ao7FO1ZZowKTcFN4GFeu6Ra6MdRybAlrPzJfhr68qH4"
      DB_SERVICE: ${DB_SERVICE}
      DB_NAME: ${MONGODB_DATABASE}
      DB_USER: ${MONGODB_USER}
      DB_PASSWORD: ${MONGODB_PASSWORD}
      DB_PORT: ${MONGODB_PORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      EMAIL_SUBJECT: ${EMAIL_SUBJECT}
      PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ../api:/usr/src/api
    ports:
      - ${API_PORT}:${API_PORT}
      - "9229:9229"
    networks:
      - network
    working_dir: /usr/src/api
    depends_on:
      - db
    command: npm run dev

  api:
    image: candi-controller-api:latest
    environment:
      PORT: ${API_PORT}
      AGENT_ADMIN_URL: ${AGENT_ADMIN_URL}
      AGENT_ADMIN_API_KEY: ${AGENT_ADMIN_API_KEY}
      DB_SERVICE: ${DB_SERVICE}
      DB_NAME: ${MONGODB_DATABASE}
      DB_USER: ${MONGODB_USER}
      DB_PASSWORD: ${MONGODB_PASSWORD}
      DB_PORT: ${MONGODB_PORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      EMAIL_SUBJECT: ${EMAIL_SUBJECT}
      PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
      LOG_LEVEL: ${LOG_LEVEL}
      S2I_SCRIPTS_PATH: ${S2I_SCRIPTS_PATH}
    volumes:
      - ./api/config:/opt/app-root/src/config
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - network
    depends_on:
      - db
    command: >
      /bin/bash -c "
      echo waiting for database...;
      sleep 15;
      ${S2I_SCRIPTS_PATH}/run;"

  #
  # db
  #
  db:
    image: centos/mongodb-36-centos7
    environment:
      MONGODB_ADMIN_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - db-data:/var/lib/mongodb/data
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - network

  maildev:
    image: djfarrelly/maildev
    networks:
      - network
    ports:
      - "8050:80"

networks:
  network:

volumes:
  db-data:
